version: '3.9'

services:
  mysql:
    image: yobasystems/alpine-mariadb
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_USER=myuser
      - MYSQL_DATABASE=mydb
